services:
  server:
    image: ghcr.io/routingallstars/graphiland/server:latest
    network_mode: "host"
    environment:
      - MAP=${MAP}

  player1:
    depends_on:
      - server
    image: ghcr.io/routingallstars/graphiland/game:${P1}
    network_mode: "host"
    environment:
      - MAP=${MAP}

  player2:
    depends_on:
      - player1
    image: ghcr.io/routingallstars/graphiland/game:${P2}
    network_mode: "host"
    environment:
      - MAP=${MAP}

  player3:
    depends_on:
      - player2
    image: ghcr.io/routingallstars/graphiland/game:${P3}
    network_mode: "host"
    environment:
      - MAP=${MAP}

  player4:
    depends_on:
      - player3
    image: ghcr.io/routingallstars/graphiland/game:${P4}
    network_mode: "host"
    environment:
      - MAP=${MAP}
