name: Batch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: 'v1'

jobs:
  game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitLab
      uses: docker/login-action@v2
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    
    - name: Run game
      run: |
        cp environments/${{ github.event.inputs.environment }}.env .env
        docker compose up
