name: Batch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: 'v1'
      runs:
        description: "Runs"
        required: true
        default: 100

jobs:
  generator:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generator.outputs.matrix }}
    steps:
      - id: generator
        run: |
          ARR=($(seq 1 1 $((${{ github.event.inputs.runs }}-1))))
          echo $ARR
          ARRAY=`printf "%s, " "${ARR[@]}"`
          echo $ARRAY
          ARRAY=$ARRAY"${{ github.event.inputs.runs }}"
          echo $ARRAY
          COMMAND='name=matrix::{"run":['$ARRAY']}'
          echo $COMMAND
          echo "::set-output "$COMMAND

  run:
    needs: generator
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.generator.outputs.matrix)}}
    steps:
      - run: |
          echo ${{ matrix.agent }}

  # game:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Login to GitLab
  #     uses: docker/login-action@v2
  #     with:
  #       registry: registry.gitlab.com
  #       username: ${{ secrets.GITLAB_USERNAME }}
  #       password: ${{ secrets.GITLAB_PASSWORD }}
    
  #   - name: Run game
  #     run: |
  #       cp environments/${{ github.event.inputs.environment }}.env .env
  #       docker compose up
