name: Build

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      needs_build: ${{ steps.check_step.outputs.needs_build }}

    steps:
      - name: Checkout local
        uses: actions/checkout@v2

      - name: Checking latest hash in gitlab
        id: check_step
        run: |
          LATEST_HASH=`cat latest-hash`
          git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/wolfee/graphi-2022.git
          cd graphi-2022
          COMMITED_HASH=`git rev-parse HEAD`
          if [[ $LATEST_HASH != $COMMITED_HASH ]]; then
            echo "The latest hashes are not the same, needs build!"
            echo "::set-output name=needs_build::TRUE"
          else
            echo "No new commits!"
            echo "::set-output name=needs_build::FALSE"
          fi

  build:
    runs-on: ubuntu-latest
    needs: check

    if: contains(needs.check.outputs.needs_build, 'TRUE')

    steps:
      - name: Checkout gitlab repository
        run: |
          echo ${{ needs.check.outputs.needs_build }}
          git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/wolfee/graphi-2022.git
