name: Build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      run: |
        git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/wolfee/graphi-2022.git

    - name: Install extra runtime
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

    - name: Install conan
      uses: turtlebrowser/get-conan@main

    - name: Configure CMake
      run: |
        cd graphi-2022
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest . -C Release
