name: Build

on:
  - push
  - workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      run: |
        git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/wolfee/graphi-2022.git

    - name: Install extra runtime
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

    - name: Install conan
      uses: turtlebrowser/get-conan@main

    - name: Configure CMake
      run: |
        cd graphi-2022
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd graphi-2022
        cmake --build build --config Release --target install

    - name: Test
      run: |
        cd graphi-2022/build
        ctest . -C Release

    - name: Build docker
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd graphi-2022
        docker build -t registry.gitlab.com/wolfee/graphi-2022/game:latest -f dockers/game ./target
