name: Game

on: workflow_dispatch

jobs:
  game:
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitLab
      uses: docker/login-action@v2
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    - name: Map 1
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=1
    - name: Map 2
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=2
    - name: Map 3
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=3
    - name: Map 4
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=4
    - name: Map 5
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=5
    - name: Map 6
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=6
    - name: Map 7
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=7
    - name: Map 8
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=8
    - name: Map 9
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=9
    - name: Map 10
      run: docker run registry.gitlab.com/wolfee/graphi-2022/game --env MAP=10
