name: Game

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        default: 'latest'

jobs:
  game:
    runs-on: ubuntu-latest

    steps:
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}
    - name: Pull
      run: docker pull ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 1
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=1 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 2
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=2 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 3
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=3 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 4
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=4 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 5
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=5 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 6
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=6 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 7
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=7 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 8
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=8 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 9
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=9 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
    - name: Map 10
      run: docker run --env TEAM=routing_allstars --env HOST=itechchallenge.dyndns.org --env PORT=63155 --env MAP=10 --env KX=1 ghcr.io/routingallstars/graphiland/game:${{ github.event.inputs.tag }}
