name: Recommit

on:
  workflow_dispatch: {}
  workflow_call:
    secrets:
      GH_USERNAME:
        required: true
      GH_PAT:
        required: true
      ECO_GITLAB_USERNAME:
        required: true
      ECO_GITLAB_PASS:
        required: true

jobs:
  recommit:
    runs-on: ubuntu-latest
    steps:
    - name: Recommit
      run: |
        git config --global user.email "routing.allstars@gmail.com"
        git config --global user.name "Routing AllStars"
        git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/wolfee001/graphiland.git
        git clone http://${{ secrets.ECO_GITLAB_USERNAME }}:${{ secrets.ECO_GITLAB_PASS }}@git-ecosim.dyndns.org:11111/graphisoft/2022/routing_allstars.git
        cd routing_allstars
        git checkout main_graphiland
        rm -rf *.c *.cpp *.h
        cp ../graphiland/game/*.cpp .
        cp ../graphiland/game/*.h .
        git add *
        git commit -m "auto puNp"
