name: Recommit

on:
  - workflow_dispatch: {}
  - workflow_call:
      secrets:
        - GITLAB_USERNAME:
            required: true
        - GITLAB_ACCESS_TOKEN:
            required: true

jobs:
  recommit:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
    - name: Recommit
      run: |
        git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/wolfee/graphi-2022.git
